--
-- PostgreSQL database dump
--

\restrict 3js6Ts4gOPm9vuiePRKfs3DxjuCxwwdtVDYZCh8pFIEIq4fET8DxbEKqk0Scf5O

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2025-11-07 13:43:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 16420)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16419)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16430)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16429)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16410)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16409)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16562)
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16536)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16535)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16398)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16397)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16386)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16385)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 16742)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 16725)
-- Name: eventos_ciudad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos_ciudad (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    departamento_id bigint NOT NULL
);


ALTER TABLE public.eventos_ciudad OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 16724)
-- Name: eventos_ciudad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos_ciudad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_ciudad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 16714)
-- Name: eventos_departamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos_departamento (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.eventos_departamento OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16713)
-- Name: eventos_departamento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos_departamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_departamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16579)
-- Name: eventos_event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos_event (
    id bigint NOT NULL,
    event_name character varying(200) NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(20) NOT NULL,
    status character varying(50) NOT NULL,
    category character varying(50) NOT NULL,
    end_datetime timestamp with time zone,
    image character varying(100),
    organizer character varying(200),
    start_datetime timestamp with time zone,
    department character varying(100) NOT NULL
);


ALTER TABLE public.eventos_event OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16578)
-- Name: eventos_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16605)
-- Name: eventos_ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos_ticket (
    id bigint NOT NULL,
    amount integer NOT NULL,
    date_of_purchase timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    unique_code character varying(100) NOT NULL,
    event_id bigint NOT NULL,
    user_id bigint NOT NULL,
    config_type_id bigint NOT NULL,
    CONSTRAINT eventos_ticket_amount_check CHECK ((amount >= 0))
);


ALTER TABLE public.eventos_ticket OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16604)
-- Name: eventos_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16621)
-- Name: eventos_ticketaccesslog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos_ticketaccesslog (
    id bigint NOT NULL,
    access_time timestamp with time zone NOT NULL,
    ip_address character varying(45),
    device_info character varying(255),
    accessed_by_id bigint,
    ticket_id bigint NOT NULL
);


ALTER TABLE public.eventos_ticketaccesslog OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16620)
-- Name: eventos_ticketaccesslog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos_ticketaccesslog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_ticketaccesslog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16594)
-- Name: eventos_tickettype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos_tickettype (
    id bigint NOT NULL,
    ticket_name character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.eventos_tickettype OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16593)
-- Name: eventos_tickettype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos_tickettype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_tickettype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 16630)
-- Name: eventos_tickettypeevent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos_tickettypeevent (
    id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    maximun_capacity integer NOT NULL,
    capacity_sold integer NOT NULL,
    event_id bigint NOT NULL,
    ticket_type_id bigint NOT NULL,
    CONSTRAINT eventos_tickettypeevent_capacity_sold_check CHECK ((capacity_sold >= 0)),
    CONSTRAINT eventos_tickettypeevent_maximun_capacity_check CHECK ((maximun_capacity >= 0))
);


ALTER TABLE public.eventos_tickettypeevent OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16629)
-- Name: eventos_tickettypeevent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos_tickettypeevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_tickettypeevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16467)
-- Name: usuarios_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    birth_date date,
    city character varying(100),
    country character varying(50),
    document character varying(30),
    phone character varying(20),
    created_at timestamp with time zone NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    document_type_id bigint
);


ALTER TABLE public.usuarios_customuser OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16488)
-- Name: usuarios_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.usuarios_customuser_groups OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16487)
-- Name: usuarios_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16466)
-- Name: usuarios_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16497)
-- Name: usuarios_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.usuarios_customuser_user_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16496)
-- Name: usuarios_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 16756)
-- Name: usuarios_tipodocumento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios_tipodocumento (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    codigo character varying(10) NOT NULL
);


ALTER TABLE public.usuarios_tipodocumento OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 16755)
-- Name: usuarios_tipodocumento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios_tipodocumento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_tipodocumento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4961 (class 2606 OID 16463)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4966 (class 2606 OID 16448)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4969 (class 2606 OID 16437)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4963 (class 2606 OID 16426)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4956 (class 2606 OID 16439)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4958 (class 2606 OID 16418)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5000 (class 2606 OID 16569)
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- TOC entry 5002 (class 2606 OID 16571)
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 4996 (class 2606 OID 16549)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4951 (class 2606 OID 16408)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4953 (class 2606 OID 16406)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 16396)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5037 (class 2606 OID 16751)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5032 (class 2606 OID 16735)
-- Name: eventos_ciudad eventos_ciudad_nombre_departamento_id_00ac4e9c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ciudad
    ADD CONSTRAINT eventos_ciudad_nombre_departamento_id_00ac4e9c_uniq UNIQUE (nombre, departamento_id);


--
-- TOC entry 5034 (class 2606 OID 16732)
-- Name: eventos_ciudad eventos_ciudad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ciudad
    ADD CONSTRAINT eventos_ciudad_pkey PRIMARY KEY (id);


--
-- TOC entry 5027 (class 2606 OID 16722)
-- Name: eventos_departamento eventos_departamento_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_departamento
    ADD CONSTRAINT eventos_departamento_nombre_key UNIQUE (nombre);


--
-- TOC entry 5029 (class 2606 OID 16720)
-- Name: eventos_departamento eventos_departamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_departamento
    ADD CONSTRAINT eventos_departamento_pkey PRIMARY KEY (id);


--
-- TOC entry 5004 (class 2606 OID 16592)
-- Name: eventos_event eventos_event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_event
    ADD CONSTRAINT eventos_event_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 16617)
-- Name: eventos_ticket eventos_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticket
    ADD CONSTRAINT eventos_ticket_pkey PRIMARY KEY (id);


--
-- TOC entry 5013 (class 2606 OID 16619)
-- Name: eventos_ticket eventos_ticket_unique_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticket
    ADD CONSTRAINT eventos_ticket_unique_code_key UNIQUE (unique_code);


--
-- TOC entry 5017 (class 2606 OID 16628)
-- Name: eventos_ticketaccesslog eventos_ticketaccesslog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticketaccesslog
    ADD CONSTRAINT eventos_ticketaccesslog_pkey PRIMARY KEY (id);


--
-- TOC entry 5006 (class 2606 OID 16603)
-- Name: eventos_tickettype eventos_tickettype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_tickettype
    ADD CONSTRAINT eventos_tickettype_pkey PRIMARY KEY (id);


--
-- TOC entry 5021 (class 2606 OID 16675)
-- Name: eventos_tickettypeevent eventos_tickettypeevent_event_id_ticket_type_id_2e44e174_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_tickettypeevent
    ADD CONSTRAINT eventos_tickettypeevent_event_id_ticket_type_id_2e44e174_uniq UNIQUE (event_id, ticket_type_id);


--
-- TOC entry 5023 (class 2606 OID 16642)
-- Name: eventos_tickettypeevent eventos_tickettypeevent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_tickettypeevent
    ADD CONSTRAINT eventos_tickettypeevent_pkey PRIMARY KEY (id);


--
-- TOC entry 4972 (class 2606 OID 16774)
-- Name: usuarios_customuser usuarios_customuser_document_84eff0c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser
    ADD CONSTRAINT usuarios_customuser_document_84eff0c2_uniq UNIQUE (document);


--
-- TOC entry 4976 (class 2606 OID 16486)
-- Name: usuarios_customuser usuarios_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser
    ADD CONSTRAINT usuarios_customuser_email_key UNIQUE (email);


--
-- TOC entry 4984 (class 2606 OID 16508)
-- Name: usuarios_customuser_groups usuarios_customuser_groups_customuser_id_group_id_aace3972_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_groups
    ADD CONSTRAINT usuarios_customuser_groups_customuser_id_group_id_aace3972_uniq UNIQUE (customuser_id, group_id);


--
-- TOC entry 4987 (class 2606 OID 16495)
-- Name: usuarios_customuser_groups usuarios_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_groups
    ADD CONSTRAINT usuarios_customuser_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4978 (class 2606 OID 16482)
-- Name: usuarios_customuser usuarios_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser
    ADD CONSTRAINT usuarios_customuser_pkey PRIMARY KEY (id);


--
-- TOC entry 4989 (class 2606 OID 16522)
-- Name: usuarios_customuser_user_permissions usuarios_customuser_user_customuser_id_permission_8dac6e14_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_user_permissions
    ADD CONSTRAINT usuarios_customuser_user_customuser_id_permission_8dac6e14_uniq UNIQUE (customuser_id, permission_id);


--
-- TOC entry 4993 (class 2606 OID 16504)
-- Name: usuarios_customuser_user_permissions usuarios_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_user_permissions
    ADD CONSTRAINT usuarios_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 16484)
-- Name: usuarios_customuser usuarios_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser
    ADD CONSTRAINT usuarios_customuser_username_key UNIQUE (username);


--
-- TOC entry 5041 (class 2606 OID 16786)
-- Name: usuarios_tipodocumento usuarios_tipodocumento_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_tipodocumento
    ADD CONSTRAINT usuarios_tipodocumento_codigo_key UNIQUE (codigo);


--
-- TOC entry 5044 (class 2606 OID 16764)
-- Name: usuarios_tipodocumento usuarios_tipodocumento_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_tipodocumento
    ADD CONSTRAINT usuarios_tipodocumento_nombre_key UNIQUE (nombre);


--
-- TOC entry 5046 (class 2606 OID 16762)
-- Name: usuarios_tipodocumento usuarios_tipodocumento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_tipodocumento
    ADD CONSTRAINT usuarios_tipodocumento_pkey PRIMARY KEY (id);


--
-- TOC entry 4959 (class 1259 OID 16464)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4964 (class 1259 OID 16459)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4967 (class 1259 OID 16460)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4954 (class 1259 OID 16445)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4998 (class 1259 OID 16577)
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- TOC entry 4994 (class 1259 OID 16560)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4997 (class 1259 OID 16561)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5035 (class 1259 OID 16753)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5038 (class 1259 OID 16752)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5030 (class 1259 OID 16741)
-- Name: eventos_ciudad_departamento_id_7475dca8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_ciudad_departamento_id_7475dca8 ON public.eventos_ciudad USING btree (departamento_id);


--
-- TOC entry 5025 (class 1259 OID 16733)
-- Name: eventos_departamento_nombre_2078c308_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_departamento_nombre_2078c308_like ON public.eventos_departamento USING btree (nombre varchar_pattern_ops);


--
-- TOC entry 5007 (class 1259 OID 16688)
-- Name: eventos_ticket_config_type_id_ccb54654; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_ticket_config_type_id_ccb54654 ON public.eventos_ticket USING btree (config_type_id);


--
-- TOC entry 5008 (class 1259 OID 16660)
-- Name: eventos_ticket_event_id_3bf5af54; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_ticket_event_id_3bf5af54 ON public.eventos_ticket USING btree (event_id);


--
-- TOC entry 5011 (class 1259 OID 16659)
-- Name: eventos_ticket_unique_code_5ad14943_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_ticket_unique_code_5ad14943_like ON public.eventos_ticket USING btree (unique_code varchar_pattern_ops);


--
-- TOC entry 5014 (class 1259 OID 16661)
-- Name: eventos_ticket_user_id_f668a01a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_ticket_user_id_f668a01a ON public.eventos_ticket USING btree (user_id);


--
-- TOC entry 5015 (class 1259 OID 16672)
-- Name: eventos_ticketaccesslog_accessed_by_id_78a5cb67; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_ticketaccesslog_accessed_by_id_78a5cb67 ON public.eventos_ticketaccesslog USING btree (accessed_by_id);


--
-- TOC entry 5018 (class 1259 OID 16673)
-- Name: eventos_ticketaccesslog_ticket_id_6d36073a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_ticketaccesslog_ticket_id_6d36073a ON public.eventos_ticketaccesslog USING btree (ticket_id);


--
-- TOC entry 5019 (class 1259 OID 16686)
-- Name: eventos_tickettypeevent_event_id_aeeca663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_tickettypeevent_event_id_aeeca663 ON public.eventos_tickettypeevent USING btree (event_id);


--
-- TOC entry 5024 (class 1259 OID 16687)
-- Name: eventos_tickettypeevent_ticket_type_id_e720ed1a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX eventos_tickettypeevent_ticket_type_id_e720ed1a ON public.eventos_tickettypeevent USING btree (ticket_type_id);


--
-- TOC entry 4970 (class 1259 OID 16775)
-- Name: usuarios_customuser_document_84eff0c2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_document_84eff0c2_like ON public.usuarios_customuser USING btree (document varchar_pattern_ops);


--
-- TOC entry 4973 (class 1259 OID 16782)
-- Name: usuarios_customuser_document_type_id_71056b48; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_document_type_id_71056b48 ON public.usuarios_customuser USING btree (document_type_id);


--
-- TOC entry 4974 (class 1259 OID 16506)
-- Name: usuarios_customuser_email_9e9473e9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_email_9e9473e9_like ON public.usuarios_customuser USING btree (email varchar_pattern_ops);


--
-- TOC entry 4982 (class 1259 OID 16519)
-- Name: usuarios_customuser_groups_customuser_id_9e05d670; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_groups_customuser_id_9e05d670 ON public.usuarios_customuser_groups USING btree (customuser_id);


--
-- TOC entry 4985 (class 1259 OID 16520)
-- Name: usuarios_customuser_groups_group_id_155d554c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_groups_group_id_155d554c ON public.usuarios_customuser_groups USING btree (group_id);


--
-- TOC entry 4990 (class 1259 OID 16533)
-- Name: usuarios_customuser_user_permissions_customuser_id_c016378e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_user_permissions_customuser_id_c016378e ON public.usuarios_customuser_user_permissions USING btree (customuser_id);


--
-- TOC entry 4991 (class 1259 OID 16534)
-- Name: usuarios_customuser_user_permissions_permission_id_9a10b097; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_user_permissions_permission_id_9a10b097 ON public.usuarios_customuser_user_permissions USING btree (permission_id);


--
-- TOC entry 4979 (class 1259 OID 16505)
-- Name: usuarios_customuser_username_44a79473_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_customuser_username_44a79473_like ON public.usuarios_customuser USING btree (username varchar_pattern_ops);


--
-- TOC entry 5039 (class 1259 OID 16787)
-- Name: usuarios_tipodocumento_codigo_3402d316_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_tipodocumento_codigo_3402d316_like ON public.usuarios_tipodocumento USING btree (codigo varchar_pattern_ops);


--
-- TOC entry 5042 (class 1259 OID 16781)
-- Name: usuarios_tipodocumento_nombre_056dec26_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_tipodocumento_nombre_056dec26_like ON public.usuarios_tipodocumento USING btree (nombre varchar_pattern_ops);


--
-- TOC entry 5048 (class 2606 OID 16454)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5049 (class 2606 OID 16449)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5047 (class 2606 OID 16440)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5057 (class 2606 OID 16572)
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_usuarios_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_usuarios_customuser_id FOREIGN KEY (user_id) REFERENCES public.usuarios_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5055 (class 2606 OID 16550)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5056 (class 2606 OID 16555)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_customuser_id FOREIGN KEY (user_id) REFERENCES public.usuarios_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5065 (class 2606 OID 16736)
-- Name: eventos_ciudad eventos_ciudad_departamento_id_7475dca8_fk_eventos_d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ciudad
    ADD CONSTRAINT eventos_ciudad_departamento_id_7475dca8_fk_eventos_d FOREIGN KEY (departamento_id) REFERENCES public.eventos_departamento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5058 (class 2606 OID 16644)
-- Name: eventos_ticket eventos_ticket_config_type_id_ccb54654_fk_eventos_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticket
    ADD CONSTRAINT eventos_ticket_config_type_id_ccb54654_fk_eventos_t FOREIGN KEY (config_type_id) REFERENCES public.eventos_tickettypeevent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5059 (class 2606 OID 16649)
-- Name: eventos_ticket eventos_ticket_event_id_3bf5af54_fk_eventos_event_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticket
    ADD CONSTRAINT eventos_ticket_event_id_3bf5af54_fk_eventos_event_id FOREIGN KEY (event_id) REFERENCES public.eventos_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5060 (class 2606 OID 16654)
-- Name: eventos_ticket eventos_ticket_user_id_f668a01a_fk_usuarios_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticket
    ADD CONSTRAINT eventos_ticket_user_id_f668a01a_fk_usuarios_customuser_id FOREIGN KEY (user_id) REFERENCES public.usuarios_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5061 (class 2606 OID 16662)
-- Name: eventos_ticketaccesslog eventos_ticketaccess_accessed_by_id_78a5cb67_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticketaccesslog
    ADD CONSTRAINT eventos_ticketaccess_accessed_by_id_78a5cb67_fk_usuarios_ FOREIGN KEY (accessed_by_id) REFERENCES public.usuarios_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5062 (class 2606 OID 16667)
-- Name: eventos_ticketaccesslog eventos_ticketaccesslog_ticket_id_6d36073a_fk_eventos_ticket_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_ticketaccesslog
    ADD CONSTRAINT eventos_ticketaccesslog_ticket_id_6d36073a_fk_eventos_ticket_id FOREIGN KEY (ticket_id) REFERENCES public.eventos_ticket(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5063 (class 2606 OID 16681)
-- Name: eventos_tickettypeevent eventos_tickettypeev_ticket_type_id_e720ed1a_fk_eventos_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_tickettypeevent
    ADD CONSTRAINT eventos_tickettypeev_ticket_type_id_e720ed1a_fk_eventos_t FOREIGN KEY (ticket_type_id) REFERENCES public.eventos_tickettype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5064 (class 2606 OID 16676)
-- Name: eventos_tickettypeevent eventos_tickettypeevent_event_id_aeeca663_fk_eventos_event_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos_tickettypeevent
    ADD CONSTRAINT eventos_tickettypeevent_event_id_aeeca663_fk_eventos_event_id FOREIGN KEY (event_id) REFERENCES public.eventos_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5051 (class 2606 OID 16509)
-- Name: usuarios_customuser_groups usuarios_customuser__customuser_id_9e05d670_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_groups
    ADD CONSTRAINT usuarios_customuser__customuser_id_9e05d670_fk_usuarios_ FOREIGN KEY (customuser_id) REFERENCES public.usuarios_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5053 (class 2606 OID 16523)
-- Name: usuarios_customuser_user_permissions usuarios_customuser__customuser_id_c016378e_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_user_permissions
    ADD CONSTRAINT usuarios_customuser__customuser_id_c016378e_fk_usuarios_ FOREIGN KEY (customuser_id) REFERENCES public.usuarios_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5054 (class 2606 OID 16528)
-- Name: usuarios_customuser_user_permissions usuarios_customuser__permission_id_9a10b097_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_user_permissions
    ADD CONSTRAINT usuarios_customuser__permission_id_9a10b097_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5050 (class 2606 OID 16776)
-- Name: usuarios_customuser usuarios_customuser_document_type_id_71056b48_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser
    ADD CONSTRAINT usuarios_customuser_document_type_id_71056b48_fk_usuarios_ FOREIGN KEY (document_type_id) REFERENCES public.usuarios_tipodocumento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5052 (class 2606 OID 16514)
-- Name: usuarios_customuser_groups usuarios_customuser_groups_group_id_155d554c_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_customuser_groups
    ADD CONSTRAINT usuarios_customuser_groups_group_id_155d554c_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-11-07 13:43:11

--
-- PostgreSQL database dump complete
--

\unrestrict 3js6Ts4gOPm9vuiePRKfs3DxjuCxwwdtVDYZCh8pFIEIq4fET8DxbEKqk0Scf5O

